### PR TITLE
Update fr locale

### PR DESCRIPTION
**Pull request by niiccolas**
All keys are now translated to French. Some questions remain:

- Would it be desirable to use the typographically correct `…` horizontal ellipsis (`&hellip;` in HTML or Unicode U+2026) instead of the current `...` (three simple dots without spacing)?
It has been used once by the previous contributor, all the other occurences are the three dots type.

- For the most part, I followed the previous contributor's translation choices. On some occasions, e.g. the whole "There was a problem …" suite of messages starting at line 238, I used a different wording, a less verbose one I believe. A second pass of standardization is needed!

- I found typos in the english part (left keys) of the document: line 171 `"… you will then be take"`.

### CODE REVIEW

**Comment by orthecreedence** [comment]
Regarding the "..." I think for simplicity, three dots, three separate characters, no spacing would be the most consistent. I _never_ use `&hellip;` in my writing or in the translated text, so it might keep things more consistent to just use "..." -- and feel free to change what the previous contributor did to use the three dots if you'd like it to be fully consistent. I give you my blessing =].

For the standardization, I personally don't mind either way. I can't speak to what's best because I don't know if the translation matches the intent of what is being said in the English version. Do what you feel is best here for your own translations, and maybe we just leave the original contributor's translations as is.

I will fix the typo! If you see any more, please let me know.

**Comment by niiccolas** [comment]
Fair enough. I wrote "typographically correct" but it really is a matter of choice/style guide. Let's stick to what you are using: three dots it is. I changed it in my last PR.

There might be a typo or, better said, a formatting error on line 128:
`"Just making sure**...d**o you really want to delete your account?"`
Isn't a space missing before the `d`, and shouldn't the `d` start with a capital letter ?

I found a consistency issue on lines 171:
`Open a **S**pace easily by hitting <kbd>s</kbd>, typing the name of the **S**pace you want, and hitting <kbd>Enter</kbd>. You will then be taken to the **B**oard selector. (…)`
and 175:
`Open the **B**oard selector by hitting`
These are the only two lines in the whole document where the words **board** and **space** start with a capital letter while being in the middle of the phrase.

**Comment by niiccolas** [comment]
One last hair to split for the day 🤓:
Line 274, the `etc` is missing its full stop (granted the following source is correct: https://www.grammarly.com/blog/et-cetera-etc/).

**Comment by orthecreedence** [comment]
1. That's a matter of style (or, perhaps, it's not but it's common enough to not have a space after the ellipses). Either way, probably will leave that one.
2. Good catch with the Space/Board inconsistency. I will fix that.
3. Also common enough that while possibly gramatically incorrect, is still in wide use (and personally I find it awkward to see something like "Share with people (friends, family, etc.).")

**Pull request merged**
