### PR TITLE
Add localization (fr + locales template)

### PR DESCRIPTION
**Pull request by ldidry**
Hello,

I localized Turtl with [i18next](http://i18next.com/) (MIT license).

Changes:
- in javascript, all sentences are surrounded by `i18next.t('Hello world')`, you can pass arguments: `i18next.t('Hello {{name}}', {name: 'world'})`
- a handlebar helper has been created (and used, of course): `{{t 'Hello {{name}}', name=user}}`
- locale files are in `locales` directory and are named like this: `fr.json`
- if there is no translation of the sentence in the language file, it uses the sentence as fallback, so there's no need for an english locale file
- there is a language template in `locales` directory, for people who wants to add a language (please update if you add sentences)
- language is detected from `navigator.language`, I let you make it an option in the user's settings (IMHO it would be a good thing to keep the language detection, have this option in the "join" form too, and then in the user's settings)
- some javascript files has been removed from `index.html` header in order to be loaded only after i18next has been initialized (have a look at `library/i18next-init.js` to see which files)
- I updated the `Content-Security-Policy` header in `views/layouts/default.html` to avoid security errors. I'm not familiar with it, so you may have a close look at it.

i18next has some [plugins](http://i18next.com/docs/ecosystem/) that could be really useful, but I let you decide to use them or not:
- [i18next-gettext-converter](https://github.com/i18next/i18next-gettext-converter) to transform .po and .mo files to i18next json and vice-versa
- [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector) to detect the language
- [i18next-localStorage-cache](https://github.com/i18next/i18next-localStorage-cache) to cache the locale file in localStorage

This has been tested on my personal Turtl server with friends, I may have missed sentences to translate, but it's no big deal to add them.

I haven't tested the apps, which (for what I understand) are just wrappers around the js app. So it needs some testing.

PS: I signed the [ICLA](https://turtl.it/contributing/) yesterday.

### CODE REVIEW

**Comment by ldidry** [comment]
Is there any reason for which the javascript files are not concatenated in only one file? I'm not talking about minification, but a simple `cat`. I got sometimes error like `FormController is not defined` (especially with Chrome wich seems to load javascript files in a different way than Firefox).

Concatenating files avoid this. I know that this make big js files (2.0M for the library/mvc files  and 174k for the files I load after i18next initialization) but once it's cached in the browser, it's very fast.

**Comment by orthecreedence** [comment]
This is *great*!! Thank you so much for putting in this work, and for following conventions.

As for having the build process create one big javascript file...since the app is only loaded locally, having separate files included is fairly cheap and makes it much easier for me to have people take console screenshots and send me the file/line number of errors they are getting.

**Comment by orthecreedence** [comment]
Ah, I see what you mean the FormController error.

I might go in and include the locales as part of the build process instead of loading the via XHR.

**Comment by orthecreedence** [comment]
Actually, yeah there's no issue using it as a web app if you have the chops to build/run it =]. What you might want to do is add a `make minify` target that runs the rest of the build process and then calls `scripts/minify` or something similar.

Also, I just updated a few things: 84163ef. Can you please pull these changes down and check if localization still works? It seems to be working just fine on my side, but I want to make sure the French locale loads as well.

**Comment by orthecreedence** [comment]
Oh, one more thing to note: you may have had problems with the load order of the scripts because of a different sort order. Yesterday, somebody went in the `scripts/include.sh` and set the sorting method by hand (if you do a pull you'll see it: `LC_ALL=C sort...`) which should fix the problems you were having with the controller load order.

**Comment by ldidry** [comment]
I already have the `LC_ALL=C sort` patch :frowning:

**Comment by ldidry** [comment]
It still works with the 84163ef commit :sparkling_heart: 

Well, as Chrome still has its FormController error, I will create an `make minify` target. Thanks :smile:

**Comment by orthecreedence** [comment]
No, thank you. I have been wanting to add localization for a while but didn't have time. Great work!

FWIW, here's the order my controllers are included:

```html
<script src="/controllers/0modules/action.js"></script>
<script src="/controllers/0modules/form.js"></script>
<script src="/controllers/0modules/header.js"></script>
<script src="/controllers/0modules/item-actions.js"></script>
<script src="/controllers/0modules/loading.js"></script>
<script src="/controllers/0modules/sidebar.js"></script>
<script src="/controllers/0modules/action.js"></script>
<script src="/controllers/0modules/form.js"></script>
<script src="/controllers/0modules/header.js"></script>
<script src="/controllers/0modules/item-actions.js"></script>
<script src="/controllers/0modules/loading.js"></script>
<script src="/controllers/0modules/nav.js"></script>
<script src="/controllers/0modules/sidebar.js"></script>
<script src="/controllers/boards/delete.js"></script>
<script src="/controllers/boards/edit.js"></script>
<script src="/controllers/boards/index.js"></script>
<script src="/controllers/boards/item.js"></script>
<script src="/controllers/boards/list.js"></script>
<script src="/controllers/boards/share/edit.js"></script>
<script src="/controllers/boards/share/index.js"></script>
<script src="/controllers/boards/share/invite.js"></script>
<script src="/controllers/boards/share/invite_email.js"></script>
<script src="/controllers/boards/share/invite_persona.js"></script>
<script src="/controllers/boards/share/item.js"></script>
<script src="/controllers/boards/share/list.js"></script>
<script src="/controllers/feedback/index.js"></script>
<script src="/controllers/help/keyboard.js"></script>
<script src="/controllers/help/markdown.js"></script>
<script src="/controllers/notes/_note_base.js"></script>
<script src="/controllers/notes/edit/boards/index.js"></script>
<script src="/controllers/notes/edit/boards/list.js"></script>
<script src="/controllers/notes/edit/file.js"></script>
<script src="/controllers/notes/edit/index.js"></script>
<script src="/controllers/notes/edit/preview.js"></script>
<script src="/controllers/notes/edit/tags/index.js"></script>
<script src="/controllers/notes/edit/tags/list.js"></script>
<script src="/controllers/notes/index.js"></script>
<script src="/controllers/notes/item.js"></script>
<script src="/controllers/notes/list.js"></script>
<script src="/controllers/notes/search.js"></script>
<script src="/controllers/notes/view.js"></script>
<script src="/controllers/pages.js"></script>
<script src="/controllers/personas/edit.js"></script>
<script src="/controllers/personas/index.js"></script>
<script src="/controllers/personas/join.js"></script>
<script src="/controllers/personas/view.js"></script>
<script src="/controllers/settings/delete_account.js"></script>
<script src="/controllers/settings/index.js"></script>
<script src="/controllers/settings/password.js"></script>
<script src="/controllers/sharing/boards/item.js"></script>
<script src="/controllers/sharing/boards/list.js"></script>
<script src="/controllers/sharing/index.js"></script>
<script src="/controllers/sharing/invites/item.js"></script>
<script src="/controllers/sharing/invites/list.js"></script>
<script src="/controllers/sync/index.js"></script>
<script src="/controllers/users/_base.js"></script>
<script src="/controllers/users/join.js"></script>
<script src="/controllers/users/login.js"></script>
<script src="/controllers/users/welcome.js"></script>
```

I was just thinking, it might not fix your issue to load everything as one script because it will still be dependent on the order the scripts are `cat`ed into the file. It might make sense to try and replicate the load order of the controllers like they are above programatically.

**Comment by ldidry** [comment]
> I was just thinking, it might not fix your issue to load everything as one script

But it is: Chrome seems to load and eval a lot of scripts concurrently, and it eval things before their dependencies. Concatenating the files really works :-)

I'll push a PR for `make minify` in a few minutes. It may be worthwhile to update the README, but I'll let you do that, you'll find the better formulation.

**Comment by orthecreedence** [comment]
Oh, weird. Chrome loads the scripts in order for me. I'm glad that works for you. Sorry for the noise.

**Comment by ldidry** [comment]
Don't worry :-) Are you working on a VM or a local server? I'm working on a distant server, and I don't have a fiber connection: that can explain that you don't have any trouble (I didn't had any troubles when working on a server in my LAN).

Oh, I forgot: thank you very much for Turtl, I love it :+1:

**Comment by orthecreedence** [comment]
That makes sense! I always work locally with Turtl, I haven't run it as a web app in years. I'm glad you like it :+1:

**Pull request merged**
