### PR TITLE
Use markdown-it instead of marked, with todo list plugin

### PR DESCRIPTION
**Pull request by ldidry**
- markdown format help updated
- locales files updated with the new strings (only french has been translated, sorry)

You will then be able to use [other plugins](https://www.npmjs.com/browse/keyword/markdown-it-plugin) for markdown-it (advice: use only those which provides access to the plugin through `window.markdownitNameOfThePlugin`)

### CODE REVIEW

**Comment by orthecreedence** [comment]
This is awesome! Thanks for the work.

Does the check list persist within the note (`note.save()`) when changed?

**Comment by ldidry** [comment]
> Does the check list persist within the note (note.save()) when changed?

Sorry, I don't understand what you mean. For now, the checklist can't be checked/unckecked: you need to write `- [ ]` or `- [X]`. So, it's just a formatting option for now and so the state is saved with the note. 

The markdown-it plugin has an option to be able to check/uncheck the list when showing as HTML, but I didn't activate it since it would require some work to save that state correctly.

**Comment by orthecreedence** [comment]
That's exactly what I wanted to know. Your implementation is great. Thanks!

**Comment by magowiz** [comment]
Sorry but I didn't understand how to use this feature : 
I wrote - [ ] list1 but I only get the bullet of unsorted list before literally "[ ] list1"
I tried this in both versions : mobile-android-0.6.4 and desktop-0.6.4 (linux x64) .
Do I need to do or install something else before I can get the checklist feature ? Does this improvement is to be released on a future version of the client ?

**Comment by ldidry** [comment]
@magowiz The patch has been merged but the clients haven't been updated. That's why it's not already working.

**Comment by berkes** [comment]
FWIW, by now thas has landed.  Note that the `-` for lists is required. So the syntax is:

    - [ ] Implement Checkboxes
    - [ ] Merge PR
    - [ ] Release new clients.

Clicking to check- and have it auto updated is still a todo: https://github.com/turtl/tracker/issues/223

**Pull request merged**
